### ISSUE TITLE
Is there something wrong with the function 'def _reorder_labels' in dataset.py?

### ISSUE THREAD

**Issue by wangyujie413** [wangguanan/Pytorch-Person-REID-Baseline-Bag-of-Tricks#8]
Why the function `def _reorder_labels ` in `dataset.py` can realize reordering the label? It just traverses through the list `samples`  and changes the value of `sample` , but does not do anything with the list `samples`.

`    def _reorder_labels(self, samples, label_index):
        ids = []
        for sample in samples:
            ids.append(sample[label_index])
        # delete repetitive elments and order
        ids = list(set(ids))
        ids.sort()
        # reorder
        for sample in samples:
            sample[label_index] = ids.index(sample[label_index])
        return samples`

**Comment by wangyujie413** [comment]
I have printed the output of the function `def _reorder_labels `, it  can really realize reordering. But why? Is it the characteristic of Python?

**Comment by wangguanan** [comment]
We first use a list (named id) to record all unrepeated labels. 
then, we use id.index(label) to replace every label.
id.index(label) return position of the label. Thus, the labels can be re-ordered. This is because the position is continuous.
for example, if id = [1, 3, 5, 7], then [id.index(1), id.index(3), id.index(5), id.index(7)] --> [0,1,2,3].
By doing so, un-continuous labels can become continuous ones.
